using System;
using System.IO;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using Debug = UnityEngine.Debug;

namespace MiniIT.Snipe.Unity.Editor
{
	/// <summary>
	/// Downloads Snipe API specs JSON for the current project and generates a strongly-typed
	/// <c>SnipeApiService.cs</c> bindings file that mirrors the server-side API.
	/// </summary>
	public static class SnipeApiGenerator
	{
		private const string SERVICE_FILE_NAME = "SnipeApiService.cs";
		private const string SPECS_FILE_NAME = "SnipeApiSpecs.json";


		#region HTTP entry point

		/// <summary>
		/// Downloads specs JSON from the Snipe server and generates C# bindings into the given directory.
		/// </summary>
		public static async Task GenerateAsync(string outputDirectory)
		{
			if (string.IsNullOrEmpty(outputDirectory))
			{
				Debug.LogError("SnipeApiGenerator.GenerateAsync - output directory is null or empty");
				return;
			}

			SnipeToolsConfig.Load();

			if (string.IsNullOrEmpty(SnipeToolsConfig.AuthKey))
			{
				Debug.LogError("SnipeApiGenerator.GenerateAsync - FAILED to get token (AuthKey is empty)");
				return;
			}

			if (SnipeToolsConfig.ProjectId <= 0)
			{
				Debug.LogError("SnipeApiGenerator.GenerateAsync - ProjectId is not configured");
				return;
			}

			Directory.CreateDirectory(outputDirectory);

			string specsJson;

			using (var client = new HttpClient())
			{
				client.DefaultRequestHeaders.Authorization =
					new AuthenticationHeaderValue("Bearer", SnipeToolsConfig.AuthKey);

				string url = $"https://edit.snipe.dev/api/v1/project/{SnipeToolsConfig.ProjectId}/code/meta";

				Debug.Log($"SnipeApiGenerator.GenerateAsync - downloading specs from {url}");

				var response = await client.GetAsync(url);

				if (!response.IsSuccessStatusCode)
				{
					Debug.LogError(
						$"SnipeApiGenerator.GenerateAsync - FAILED to download Specs; HTTP status: {(int)response.StatusCode} - {response.StatusCode}");
					return;
				}

				specsJson = await response.Content.ReadAsStringAsync();
			}

			// Save raw specs JSON alongside generated code for debugging.
			try
			{
				var specsPath = Path.Combine(outputDirectory, SPECS_FILE_NAME);
				File.WriteAllText(specsPath, specsJson, Encoding.UTF8);
			}
			catch (Exception e)
			{
				Debug.LogWarning($"SnipeApiGenerator.GenerateAsync - failed to save specs file: {e}");
			}

			await GenerateFromJsonAsync(outputDirectory, specsJson);
		}

		/// <summary>
		/// Generates bindings from an already downloaded JSON document and writes them into the directory.
		/// </summary>
		public static Task GenerateFromJsonAsync(string outputDirectory, string specsJson)
		{
			if (string.IsNullOrEmpty(specsJson))
			{
				Debug.LogError("SnipeApiGenerator.GenerateFromJsonAsync - specsJson is null or empty");
				return Task.CompletedTask;
			}

			try
			{
				var root = ParseJson(specsJson);
				if (root == null)
				{
					Debug.LogError("SnipeApiGenerator.GenerateFromJsonAsync - failed to parse specs JSON");
					return Task.CompletedTask;
				}

				string code = GenerateCode(root);

				Directory.CreateDirectory(outputDirectory);
				var servicePath = Path.Combine(outputDirectory, SERVICE_FILE_NAME);
				File.WriteAllText(servicePath, code, Encoding.UTF8);

				Debug.Log($"SnipeApiGenerator - generated {SERVICE_FILE_NAME} at path: {servicePath}");
			}
			catch (Exception e)
			{
				Debug.LogError($"SnipeApiGenerator.GenerateFromJsonAsync - exception while generating: {e}");
			}

			return Task.CompletedTask;
		}

		#endregion

		#region Code generation

		private static string GenerateCode(MetagenRoot root)
		{
			var sb = new StringBuilder(64 * 1024);

			GenerateFileHeader(sb, root);
			GenerateNamespaceOpen(sb);
			GenerateContextFactory(sb, root);
			GenerateExtensions(sb);
			GenerateServiceClass(sb, root);
			GenerateModules(sb, root);
			GenerateTypes(sb, root);
			GenerateUserAttributes(sb, root);
			GenerateTables(sb, root);
			GenerateNamespaceClose(sb);

			return sb.ToString();
		}

		private static void GenerateFileHeader(StringBuilder sb, MetagenRoot root)
		{
			var projectId = string.IsNullOrEmpty(root.projectStringID) ? root.projectID.ToString() : root.projectStringID;
			var version = string.IsNullOrEmpty(root.snipeVersion) ? "8.0" : root.snipeVersion;

			DateTime generatedAt;
			if (!DateTime.TryParse(root.generatedAt, out generatedAt))
				generatedAt = DateTime.Now;

			sb.AppendLine("// <auto-generated />");
			sb.Append("// Snipe Api v").Append(version)
				.Append(" for project ").Append(projectId)
				.Append(", ").AppendLine(generatedAt.ToUniversalTime().ToString("dd MMM yyyy, HH:mm:ss UTC"));
			sb.AppendLine("// THIS FILE IS AUTO-GENERATED. ALL EDITS WILL BE LOST.");
			sb.AppendLine();
			sb.AppendLine("using System;");
			sb.AppendLine("using System.Collections.Generic;");
			sb.AppendLine("using System.Collections;");
			sb.AppendLine("using MiniIT.Snipe.Configuration;");
			sb.AppendLine("using MiniIT.Threading;");
			sb.AppendLine();
		}

		private static void GenerateNamespaceOpen(StringBuilder sb)
		{
			sb.AppendLine("namespace MiniIT.Snipe.Api");
			sb.AppendLine("{");
		}

		private static void GenerateNamespaceClose(StringBuilder sb)
		{
			sb.AppendLine("}");
		}

		private static void GenerateContextFactory(StringBuilder sb, MetagenRoot root)
		{
			Indent(sb, 1).AppendLine("public sealed class SnipeApiContextFactory : AbstractSnipeApiContextFactory, ISnipeContextAndTablesFactory");
			Indent(sb, 1).AppendLine("{");
			Indent(sb, 2).AppendLine("public SnipeApiContextFactory(ISnipeManager tablesProvider, SnipeConfigBuilder configBuilder)");
			Indent(sb, 3).AppendLine(": base(tablesProvider, configBuilder) { }");
			sb.AppendLine();

			// Parse timezone from spec (format: "+0300" or "-0500")
			double timezoneHours = 3.0; // default
			if (!string.IsNullOrEmpty(root.timeZone))
			{
				if (root.timeZone.StartsWith("+") || root.timeZone.StartsWith("-"))
				{
					string sign = root.timeZone.Substring(0, 1);
					string hoursStr = root.timeZone.Substring(1, 2);
					string minutesStr = root.timeZone.Length > 3 ? root.timeZone.Substring(3, 2) : "00";
					if (int.TryParse(hoursStr, out int hours) && int.TryParse(minutesStr, out int minutes))
					{
						timezoneHours = hours + (minutes / 60.0);
						if (sign == "-")
							timezoneHours = -timezoneHours;
					}
				}
			}

			Indent(sb, 2).Append("public override TimeSpan GetServerTimeZoneOffset() => TimeSpan.FromHours(")
				.Append(timezoneHours.ToString("F1", System.Globalization.CultureInfo.InvariantCulture)).AppendLine(");");
			Indent(sb, 2).AppendLine("public override AbstractSnipeApiService CreateSnipeApiService(SnipeCommunicator communicator, AuthSubsystem auth) => new SnipeApiService(communicator, auth);");
			Indent(sb, 2).AppendLine("public SnipeApiTables CreateSnipeApiTables() => new SnipeTables();");
			Indent(sb, 1).AppendLine("}");
			sb.AppendLine();
		}

		private static void GenerateExtensions(StringBuilder sb)
		{
			Indent(sb, 1).AppendLine("public static class SnipeApiExtensions");
			Indent(sb, 1).AppendLine("{");
			Indent(sb, 2).AppendLine("public static SnipeApiService GetApi(this SnipeContext context) => (SnipeApiService)(context as SnipeApiContext).GetSnipeApiService();");
			Indent(sb, 2).AppendLine("public static SnipeTables GetTables(this ISnipeTablesProvider tablesProvider) => (SnipeTables)tablesProvider.GetSnipeTables();");
			Indent(sb, 1).AppendLine("}");
			sb.AppendLine();
		}

		private static void GenerateServiceClass(StringBuilder sb, MetagenRoot root)
		{
			Indent(sb, 1).AppendLine("public sealed class SnipeApiService : AbstractSnipeApiService");
			Indent(sb, 1).AppendLine("{");

			// Module properties
			if (root.modules != null)
			{
				foreach (var module in root.modules)
				{
					if (string.IsNullOrEmpty(module.name))
						continue;

					string moduleClass = "SnipeApiModule" + module.name;
					Indent(sb, 2).Append("public ").Append(moduleClass).Append(' ').Append(module.name).Append(" { get; }").AppendLine();
				}
			}

			sb.AppendLine();
			Indent(sb, 2).AppendLine("public SnipeApiService(SnipeCommunicator communicator, AuthSubsystem auth)");
			Indent(sb, 2).AppendLine("\t: base(communicator, auth)");
			Indent(sb, 2).AppendLine("{");

			if (root.modules != null)
			{
				foreach (var module in root.modules)
				{
					if (string.IsNullOrEmpty(module.name))
						continue;

					string moduleClass = "SnipeApiModule" + module.name;
					Indent(sb, 3).Append(module.name).Append(" = new ").Append(moduleClass).AppendLine("(this);");
				}
			}

			Indent(sb, 2).AppendLine("}");
			sb.AppendLine();

			// Mergeable requests
			Indent(sb, 2).AppendLine("protected override void InitMergeableRequestTypes()");
			Indent(sb, 2).AppendLine("{");

			if (root.mergeableRequests != null)
			{
				foreach (var mr in root.mergeableRequests)
				{
					if (string.IsNullOrEmpty(mr.messageType))
						continue;

					Indent(sb, 3).Append("AddMergeableRequestType(\"").Append(mr.messageType).AppendLine("\");");
				}
			}

			Indent(sb, 2).AppendLine("}");
			Indent(sb, 1).AppendLine("}");
			sb.AppendLine();
		}

		private static void GenerateModules(StringBuilder sb, MetagenRoot root)
		{
			if (root.modules == null)
				return;

			foreach (var module in root.modules)
			{
				if (string.IsNullOrEmpty(module.name))
					continue;

				string moduleClass = "SnipeApiModule" + module.name;
				bool isUserAttr = module.name == "UserAttr";

				Indent(sb, 1).Append("public sealed class ").Append(moduleClass).Append(" : SnipeApiModule").AppendLine();
				Indent(sb, 1).AppendLine("{");

				// Special properties for UserAttr module
				if (isUserAttr)
				{
					Indent(sb, 2).AppendLine("public UserAttributes UserAttributes { get; private set; }");
					Indent(sb, 2).AppendLine("public bool Initialized { get; private set; }");
					sb.AppendLine();
				}

				Indent(sb, 2).Append("internal ").Append(moduleClass).Append("(SnipeApiService snipeApiService) : base(snipeApiService)").AppendLine();
				Indent(sb, 2).AppendLine("{");

				// Special initialization for UserAttr module
				if (isUserAttr)
				{
					Indent(sb, 3).AppendLine("UserAttributes = new UserAttributes(snipeApiService);");
				}

				bool hasResponses = module.responses != null && module.responses.Length > 0;
				if (hasResponses)
				{
					Indent(sb, 3).AppendLine("SubscribeOnMessageReceived(OnMessageReceived);");
				}

				Indent(sb, 2).AppendLine("}");
				sb.AppendLine();

				// Methods
				if (module.methods != null)
				{
					foreach (var method in module.methods)
					{
						GenerateMethod(sb, method);
					}
				}

				// Responses -> events
				if (module.responses != null && module.responses.Length > 0)
				{
					foreach (var response in module.responses)
					{
						GenerateResponseEvent(sb, response);
					}

					GenerateOnMessageReceived(sb, module);
				}

				Indent(sb, 1).AppendLine("}");
				sb.AppendLine();
			}
		}

		private static void GenerateMethod(StringBuilder sb, MetagenMethod method)
		{
			if (method == null || string.IsNullOrEmpty(method.callName) || string.IsNullOrEmpty(method.messageType))
				return;

			// Extract method name from messageType: "attr.getAll" -> "GetAll", "attr.getMulti" -> "GetMulti"
			// Split by '.' and take the right part, then capitalize first letter
			string methodName = method.messageType;
			int dotIndex = methodName.IndexOf('.');
			if (dotIndex >= 0 && dotIndex < methodName.Length - 1)
			{
				methodName = methodName.Substring(dotIndex + 1);
				if (methodName.Length > 0)
				{
					methodName = char.ToUpperInvariant(methodName[0]) + methodName.Substring(1);
				}
			}
			string callbackName = methodName + "Callback";

			// Delegate
			Indent(sb, 2).Append("public delegate void ").Append(callbackName).Append("(");
			sb.Append("string errorCode");

			if (method.outputs != null)
			{
				foreach (var field in method.outputs)
				{
					// Skip errorCode in outputs since it's always the first parameter
					if (field.name == "errorCode")
						continue;

					string csType = MapTypeToCs(field.type, field.itemType);
					Indent(sb, 0).Append(",").AppendLine();
					// For GetAll, use field name directly (data), otherwise prefix with o_
					string paramName = (method.messageType == "attr.getAll" && field.name == "data")
						? field.name
						: "o_" + field.name;
					Indent(sb, 3).Append(csType).Append(' ').Append(paramName);
				}
			}

			sb.Append(");").AppendLine();

			// XML doc with inputs, outputs, and error codes - standard XML doc format
			Indent(sb, 2).AppendLine("/// <summary>");
			Indent(sb, 2).Append("/// __").Append(method.messageType).Append("__").AppendLine();

			// Description from doc - combine into paragraphs
			if (method.doc != null && method.doc.Length > 0)
			{
				var descriptionBuilder = new StringBuilder();
				foreach (var line in method.doc)
				{
					if (string.IsNullOrWhiteSpace(line))
					{
						if (descriptionBuilder.Length > 0)
						{
							Indent(sb, 2).Append("/// <para>").Append(EscapeXml(descriptionBuilder.ToString().Trim())).AppendLine("</para>");
							descriptionBuilder.Clear();
						}
					}
					else
					{
						if (descriptionBuilder.Length > 0)
							descriptionBuilder.Append(" ");
						descriptionBuilder.Append(line.Trim());
					}
				}
				if (descriptionBuilder.Length > 0)
				{
					Indent(sb, 2).Append("/// <para>").Append(EscapeXml(descriptionBuilder.ToString().Trim())).AppendLine("</para>");
				}
			}

			// Input section
			if (method.inputs != null && method.inputs.Length > 0)
			{
				Indent(sb, 2).Append("/// Input:<ul>").AppendLine();
				foreach (var field in method.inputs)
				{
					string optional = field.optional ? " (optional)" : "";
					string csType = MapTypeToCs(field.type, field.itemType);
					string typeName = GetTypeDisplayName(csType);
					string desc = !string.IsNullOrEmpty(field.description) ? ". " + field.description : "";
					Indent(sb, 2).Append("/// <li>`").Append(field.name).Append("`").Append(optional)
						.Append(" - `").Append(typeName).Append("`").Append(desc).AppendLine("</li>");
				}
				Indent(sb, 2).AppendLine("/// </ul><br/>");
			}

			// Output section
			if (method.outputs != null && method.outputs.Length > 0)
			{
				Indent(sb, 2).Append("/// Output:<ul>").AppendLine();
				foreach (var field in method.outputs)
				{
					string csType = MapTypeToCs(field.type, field.itemType);
					string typeName = GetTypeDisplayName(csType);
					string desc = !string.IsNullOrEmpty(field.description) ? ". " + field.description : "";
					Indent(sb, 2).Append("/// <li>`").Append(field.name).Append("` - `").Append(typeName)
						.Append("`").Append(desc).AppendLine("</li>");
				}
				Indent(sb, 2).AppendLine("/// </ul><br/>");
			}

			// Error codes section
			if (method.errorCodes != null && method.errorCodes.Length > 0)
			{
				Indent(sb, 2).Append("/// Error codes:<ul>").AppendLine();
				foreach (var errorCode in method.errorCodes)
				{
					if (string.IsNullOrWhiteSpace(errorCode))
						continue;
					Indent(sb, 2).Append("/// <li>").Append(EscapeXml(errorCode)).AppendLine("</li>");
				}
				Indent(sb, 2).AppendLine("/// </ul><br/>");
			}
			Indent(sb, 2).AppendLine("/// </summary>");

			// Method signature
			Indent(sb, 2).Append("public bool ").Append(methodName).Append("(");

			// inputs as parameters
			bool firstParam = true;
			if (method.inputs != null)
			{
				foreach (var field in method.inputs)
				{
					if (!firstParam)
					{
						sb.Append(", ");
					}
					firstParam = false;

					string csType = MapTypeToCs(field.type, field.itemType);
					sb.Append(csType).Append(' ').Append(field.name);
				}
			}

			if (!firstParam)
			{
				sb.Append(", ");
			}

			sb.Append(callbackName).Append(" callback = null)");
			sb.AppendLine();
			Indent(sb, 2).AppendLine("{");

			// request_data dictionary
			Indent(sb, 3).AppendLine("Dictionary<string, object> request_data = new Dictionary<string, object>()");
			Indent(sb, 3).AppendLine("{");

			if (method.inputs != null)
			{
				for (int i = 0; i < method.inputs.Length; i++)
				{
					var field = method.inputs[i];
					Indent(sb, 4).Append("[\"").Append(field.name).Append("\"] = ").Append(field.name);
					sb.Append(i < method.inputs.Length - 1 ? "," : string.Empty).AppendLine();
				}
			}

			Indent(sb, 3).AppendLine("};");

			// CreateRequest
			Indent(sb, 3).Append("var request = CreateRequest(\"").Append(method.messageType).Append("\", request_data);").AppendLine();
			sb.AppendLine();
			Indent(sb, 3).AppendLine("if (request == null)");
			Indent(sb, 4).AppendLine("return false;");
			sb.AppendLine();

			// Request callback - special handling for UserAttr.GetAll
			bool isUserAttrGetAll = method.messageType == "attr.getAll";
			if (isUserAttrGetAll)
			{
				Indent(sb, 3).AppendLine("request.Request(async (error_code, response_data) =>");
				Indent(sb, 3).AppendLine("{");
				Indent(sb, 4).AppendLine("this.Initialized = true;");
				Indent(sb, 4).AppendLine("await AlterTask.Yield();");
				Indent(sb, 4).Append("callback?.Invoke(error_code,").AppendLine();
				Indent(sb, 5).AppendLine("this.UserAttributes);");
			}
			else
			{
				Indent(sb, 3).AppendLine("request.Request((error_code, response_data) =>");
				Indent(sb, 3).AppendLine("{");

				if (method.outputs != null && method.outputs.Length > 0)
				{
					foreach (var field in method.outputs)
					{
						// Skip errorCode in outputs since it's always the first parameter
						if (field.name == "errorCode")
							continue;
						GenerateOutputFieldExtraction(sb, field, 4);
					}

					Indent(sb, 4).Append("callback?.Invoke(error_code");
					foreach (var field in method.outputs)
					{
						// Skip errorCode in outputs since it's always the first parameter
						if (field.name == "errorCode")
							continue;

						string paramName = (method.messageType == "attr.getAll" && field.name == "data")
							? "this.UserAttributes"
							: "o_" + field.name;
						sb.Append(", ").Append(paramName);
					}
					sb.Append(");").AppendLine();
				}
				else
				{
					Indent(sb, 4).AppendLine("callback?.Invoke(error_code);");
				}
			}

			Indent(sb, 3).AppendLine("});");
			Indent(sb, 3).AppendLine("return true;");
			Indent(sb, 2).AppendLine("}");
			sb.AppendLine();
		}

		private static void GenerateOutputFieldExtraction(StringBuilder sb, MetagenField field, int indent)
		{
			string csType = MapTypeToCs(field.type, field.itemType);
			string varName = "o_" + field.name;

			if (field.type == "string")
			{
				Indent(sb, indent).Append(csType).Append(' ').Append(varName)
					.Append(" = response_data.SafeGetString(\"").Append(field.name).Append("\");").AppendLine();
			}
			else if (field.type == "int" || field.type == "float" || field.type == "boolean")
			{
				string genericType = csType == "bool" ? "bool" : csType;
				Indent(sb, indent).Append(csType).Append(' ').Append(varName)
					.Append(" = response_data.SafeGetValue<").Append(genericType).Append(">(\"")
					.Append(field.name).Append("\");").AppendLine();
			}
			else if (field.type == "array")
			{
				Indent(sb, indent).Append("var ").Append(varName).Append(" = new ").Append(csType).Append("();")
					.AppendLine();
				Indent(sb, indent).Append("if (response_data[\"").Append(field.name)
					.Append("\"] is IList src_").Append(field.name).Append(')').AppendLine();
				Indent(sb, indent).AppendLine("{");

				// assume arrays of simple dictionaries / scalars; keep generic
				Indent(sb, indent + 1).Append("foreach (var o in src_").Append(field.name).Append(')').AppendLine();
				Indent(sb, indent + 2).Append(varName).Append(".Add((").Append(GetArrayItemType(csType))
					.Append(")o);").AppendLine();

				Indent(sb, indent).AppendLine("}");
			}
			else
			{
				// custom type / json object – try dictionary-based
				Indent(sb, indent).Append(csType).Append(' ').Append(varName)
					.Append(" = new ").Append(csType)
					.Append("(response_data[\"").Append(field.name).Append("\"] as Dictionary<string, object>);")
					.AppendLine();
			}
		}

		private static string GetArrayItemType(string listType)
		{
			int start = listType.IndexOf('<');
			int end = listType.LastIndexOf('>');
			if (start >= 0 && end > start)
				return listType.Substring(start + 1, end - start - 1);
			return "object";
		}

		private static void GenerateResponseEvent(StringBuilder sb, MetagenResponse response)
		{
			if (response == null || string.IsNullOrEmpty(response.msgType) || string.IsNullOrEmpty(response.callName))
				return;

			string handlerName = response.callName + "Handler";
			string eventName = "On" + response.callName;

			Indent(sb, 2).Append("public delegate void ").Append(handlerName).Append("(");
			sb.Append("string errorCode");

			if (response.fields != null)
			{
				foreach (var field in response.fields)
				{
					string csType = MapTypeToCs(field.type, field.itemType);
					Indent(sb, 0).Append(",").AppendLine();
					Indent(sb, 3).Append(csType).Append(' ').Append("o_").Append(field.name);
				}
			}

			sb.Append(");").AppendLine();
			Indent(sb, 2).Append("public event ").Append(handlerName).Append(' ').Append(eventName).AppendLine(";");
			sb.AppendLine();
		}

		private static void GenerateOnMessageReceived(StringBuilder sb, MetagenModule module)
		{
			Indent(sb, 2).AppendLine("private void OnMessageReceived(string message_type, string error_code, IDictionary<string, object> response_data, int request_id)");
			Indent(sb, 2).AppendLine("{");

			bool first = true;
			foreach (var response in module.responses)
			{
				if (response == null || string.IsNullOrEmpty(response.msgType) || string.IsNullOrEmpty(response.callName))
					continue;

				string eventName = "On" + response.callName;

				Indent(sb, 3).Append(first ? "if" : "else if").Append(" (message_type == \"")
					.Append(response.msgType).Append("\")").AppendLine();
				Indent(sb, 3).AppendLine("{");

				if (response.fields != null && response.fields.Length > 0)
				{
					foreach (var field in response.fields)
					{
						GenerateOutputFieldExtraction(sb, field, 4);
					}

					Indent(sb, 4).Append(eventName).Append("?.Invoke(error_code");
					foreach (var field in response.fields)
					{
						sb.Append(", ").Append("o_").Append(field.name);
					}
					sb.Append(");").AppendLine();
				}
				else
				{
					Indent(sb, 4).Append(eventName).AppendLine("?.Invoke(error_code);");
				}

				Indent(sb, 3).AppendLine("}");

				first = false;
			}

			Indent(sb, 2).AppendLine("}");
			sb.AppendLine();
		}

		private static void GenerateTypes(StringBuilder sb, MetagenRoot root)
		{
			if (root.types == null)
				return;

			foreach (var type in root.types)
			{
				if (string.IsNullOrEmpty(type.name))
					continue;

				Indent(sb, 1).AppendLine("[System.Serializable]");
				Indent(sb, 1).Append("public sealed class ").Append(type.name).Append(" : IMapConvertible").AppendLine();
				Indent(sb, 1).AppendLine("{");

				// fields
				if (type.fields != null)
				{
					foreach (var field in type.fields)
					{
						string csType = MapTypeToCs(field.type, field.itemType);
						Indent(sb, 2).Append("public ").Append(csType).Append(' ').Append(field.name).Append(";")
							.AppendLine();
					}
				}

				// default ctor
				Indent(sb, 2).Append("public ").Append(type.name).Append("() {}").AppendLine();

				// ctor from map
				Indent(sb, 2).Append("public ").Append(type.name).Append("(IDictionary<string, object> data = null)").AppendLine();
				Indent(sb, 2).AppendLine("{");
				Indent(sb, 3).AppendLine("if (data == null) return;");

				if (type.fields != null)
				{
					foreach (var field in type.fields)
					{
						var csType = MapTypeToCs(field.type, field.itemType);

						if (field.type == "string")
						{
							Indent(sb, 3).Append("this.").Append(field.name).Append(" = data.SafeGetString(\"")
								.Append(field.name).Append("\");").AppendLine();
						}
						else if (field.type == "int" || field.type == "float" || field.type == "boolean")
						{
							string genericType = csType == "bool" ? "bool" : csType;
							Indent(sb, 3).Append("this.").Append(field.name).Append(" = data.SafeGetValue<")
								.Append(genericType).Append(">(\"").Append(field.name).Append("\");").AppendLine();
						}
						else if (field.type == "array")
						{
							string listType = csType;
							string itemType = GetArrayItemType(listType);

							Indent(sb, 3).Append("var o_").Append(field.name).Append(" = new ").Append(listType)
								.Append("();").AppendLine();
							Indent(sb, 3).Append("if (data[\"").Append(field.name)
								.Append("\"] is IList src_").Append(field.name).Append(')').AppendLine();
							Indent(sb, 3).AppendLine("{");
							Indent(sb, 4).Append("foreach (").Append(itemType).Append(" o in src_").Append(field.name)
								.Append(')').AppendLine();
							Indent(sb, 5).Append("o_").Append(field.name).Append(".Add(o);").AppendLine();
							Indent(sb, 3).AppendLine("}");
							Indent(sb, 3).Append("this.").Append(field.name).Append(" = o_").Append(field.name)
								.Append(";").AppendLine();
						}
						else
						{
							Indent(sb, 3).Append("this.").Append(field.name).Append(" = new ").Append(csType)
								.Append("(data[\"").Append(field.name).Append("\"] as Dictionary<string, object>);")
								.AppendLine();
						}
					}
				}

				Indent(sb, 2).AppendLine("}");
				sb.AppendLine();

				// implicit operator
				Indent(sb, 2).Append("public static implicit operator ").Append(type.name)
					.Append("(Dictionary<string, object> data)").AppendLine();
				Indent(sb, 2).AppendLine("{");
				Indent(sb, 3).Append("return new ").Append(type.name).Append("(data);").AppendLine();
				Indent(sb, 2).AppendLine("}");
				sb.AppendLine();

				// ToMap
				Indent(sb, 2).AppendLine("public IDictionary<string, object> ToMap()");
				Indent(sb, 2).AppendLine("{");
				Indent(sb, 3).AppendLine("return new Dictionary<string, object>()");
				Indent(sb, 3).AppendLine("{");

				if (type.fields != null)
				{
					for (int i = 0; i < type.fields.Length; i++)
					{
						var field = type.fields[i];
						Indent(sb, 4).Append("[\"").Append(field.name).Append("\"] = this.").Append(field.name);
						sb.Append(i < type.fields.Length - 1 ? "," : string.Empty).AppendLine();
					}
				}

				Indent(sb, 3).AppendLine("};");
				Indent(sb, 2).AppendLine("}");
				Indent(sb, 1).AppendLine("}");
				sb.AppendLine();
			}
		}

		private static void GenerateUserAttributes(StringBuilder sb, MetagenRoot root)
		{
			if (root.userAttributes == null || root.userAttributes.Length == 0)
				return;

			Indent(sb, 1).AppendLine("public sealed class UserAttributes : SnipeApiUserAttributes");
			Indent(sb, 1).AppendLine("{");

			foreach (var attr in root.userAttributes)
			{
				if (string.IsNullOrEmpty(attr.stringID))
					continue;

				string csType = MapTypeToCs(attr.type, null);
				bool isReadOnly = attr.clientWrite == "internal" || attr.clientWrite == "none";
				string attributeType = isReadOnly ? $"SnipeApiReadOnlyUserAttribute<{csType}>" : $"SnipeApiUserAttribute<{csType}>";
				Indent(sb, 2).Append("public ").Append(attributeType).Append(' ').Append(attr.stringID).AppendLine(" { get; }");
			}

			sb.AppendLine();
			Indent(sb, 2).AppendLine("public UserAttributes(SnipeApiService snipeApiService) : base(snipeApiService)");
			Indent(sb, 2).AppendLine("{");

			foreach (var attr in root.userAttributes)
			{
				if (string.IsNullOrEmpty(attr.stringID))
					continue;

				string csType = MapTypeToCs(attr.type, null);
				bool isReadOnly = attr.clientWrite == "internal" || attr.clientWrite == "none";
				string attributeType = isReadOnly ? $"SnipeApiReadOnlyUserAttribute<{csType}>" : $"SnipeApiUserAttribute<{csType}>";
				Indent(sb, 3).Append(attr.stringID).Append(" = RegisterAttribute(new ").Append(attributeType)
					.Append("(snipeApiService, \"").Append(attr.stringID).AppendLine("\"));");
			}

			Indent(sb, 2).AppendLine();
			Indent(sb, 2).AppendLine("}");
			Indent(sb, 1).AppendLine("}");
			sb.AppendLine();
		}

		private static void GenerateTables(StringBuilder sb, MetagenRoot root)
		{
			if (root.tables == null || root.tables.Length == 0)
				return;

			// SnipeTables
			Indent(sb, 1).AppendLine("public sealed class SnipeTables : SnipeApiTables");
			Indent(sb, 1).AppendLine("{");

			foreach (var table in root.tables)
			{
				if (string.IsNullOrEmpty(table.stringID))
					continue;

				string itemClassName = "SnipeTable" + table.stringID + "Item";
				Indent(sb, 2).Append("public SnipeTable<").Append(itemClassName).Append("> ").Append(table.stringID)
					.Append(" { get; }").AppendLine();
			}

			sb.AppendLine();
			Indent(sb, 2).AppendLine("public SnipeTables()");
			Indent(sb, 2).AppendLine("{");

			foreach (var table in root.tables)
			{
				if (string.IsNullOrEmpty(table.stringID))
					continue;

				string itemClassName = "SnipeTable" + table.stringID + "Item";
				Indent(sb, 3).Append(table.stringID).Append(" = RegisterTable(new SnipeTable<")
					.Append(itemClassName).Append(">(), \"").Append(table.stringID).Append("\");").AppendLine();
			}

			Indent(sb, 2).AppendLine("}");
			Indent(sb, 1).AppendLine("}");
			sb.AppendLine();

			// Table item classes
			foreach (var table in root.tables)
			{
				if (string.IsNullOrEmpty(table.stringID))
					continue;

				string itemClassName = "SnipeTable" + table.stringID + "Item";

				Indent(sb, 1).AppendLine("[System.Serializable]");
				Indent(sb, 1).Append("public sealed class ").Append(itemClassName).Append(" : SnipeTableItem")
					.AppendLine();
				Indent(sb, 1).AppendLine("{");

				if (table.fields != null)
				{
					foreach (var field in table.fields)
					{
						if (!string.IsNullOrEmpty(field.name))
						{
							Indent(sb, 2).Append("/// <summary>").Append(field.name).AppendLine("</summary>");
						}

						Indent(sb, 2).AppendLine("#if UNITY_EDITOR");
						Indent(sb, 2).AppendLine("[field:UnityEngine.SerializeField]");
						Indent(sb, 2).AppendLine("#endif");

						string csType = MapTableTypeToCs(field.type);
						Indent(sb, 2).Append("public ").Append(csType).Append(' ').Append(field.id)
							.Append(" { get; set; }").AppendLine();
					}
				}

				Indent(sb, 1).AppendLine("}");
				sb.AppendLine();
			}
		}

		#endregion

		#region Helpers


		private static StringBuilder Indent(StringBuilder sb, int level)
		{
			for (int i = 0; i < level; i++)
				sb.Append('\t');
			return sb;
		}

		private static string EscapeXml(string text)
		{
			if (string.IsNullOrEmpty(text))
				return string.Empty;

			return text
				.Replace("&", "&amp;")
				.Replace("<", "&lt;")
				.Replace(">", "&gt;");
		}

		private static string MapTypeToCs(string type, string itemType)
		{
			if (string.IsNullOrEmpty(type))
				return "object";

			switch (type)
			{
				case "string":
					return "string";
				case "int":
					return "int";
				case "float":
					return "float";
				case "boolean":
					return "bool";
				case "object":
					return "object";
				case "array":
					{
						string elementType = MapTypeToCs(itemType, null);
						return $"List<{elementType}>";
					}
				case "Dynamic":
					return "Dictionary<string, object>";
				default:
					return type;
			}
		}

		private static string GetTypeDisplayName(string csType)
		{
			if (string.IsNullOrEmpty(csType))
				return "object";

			// Convert C# types to display names used in XML docs
			switch (csType)
			{
				case "string":
					return "String";
				case "int":
					return "Int";
				case "float":
					return "Float";
				case "bool":
					return "Bool";
				case "object":
					return "object";
				case "Dictionary<string, object>":
					return "object";
				default:
					// For List<T>, extract T and format as "Array<T>"
					if (csType.StartsWith("List<") && csType.EndsWith(">"))
					{
						string elementType = csType.Substring(5, csType.Length - 6);
						string displayElementType = GetTypeDisplayName(elementType);
						return $"Array of {displayElementType}";
					}
					return csType;
			}
		}

		private static string MapTableTypeToCs(string type)
		{
			if (string.IsNullOrEmpty(type))
				return "string";

			switch (type)
			{
				case "int":
					return "int";
				case "float":
					return "float";
				case "boolean":
					return "bool";
				default:
					return "string";
			}
		}

		#endregion

		#region JSON Parsing

		private static MetagenRoot ParseJson(string json)
		{
			try
			{
				var root = fastJSON.JSON.ToObject<MetagenRoot>(json);
				return root;
			}
			catch (Exception e)
			{
				Debug.LogError($"SnipeApiGenerator.ParseJson - exception: {e}");
				return null;
			}
		}

		#endregion

		#region Spec DTOs

		private sealed class MetagenRoot
		{
			public int projectID;
			public string projectStringID;
			public string projectName;
			public string snipeVersion;
			public string generatedAt;
			public string timeZone;
			public MetagenModule[] modules;
			public MetagenType[] types;
			public MetagenUserAttribute[] userAttributes;
			public MetagenTable[] tables;
			public MetagenMergeableRequest[] mergeableRequests;
		}

		private sealed class MetagenModule
		{
			public string name;
			public bool hasResponses;
			public MetagenMethod[] methods;
			public MetagenResponse[] responses;
		}

		private sealed class MetagenMethod
		{
			public string callName;
			public string messageType;
			public string[] doc;
			public MetagenField[] inputs;
			public MetagenField[] outputs;
			public string[] errorCodes;
		}

		private sealed class MetagenResponse
		{
			public string msgType;
			public string callName;
			public string[] doc;
			public MetagenField[] fields;
		}

		private sealed class MetagenField
		{
			public string name;
			public string type;
			public string itemType;
			public bool optional;
			public string description;
		}

		private sealed class MetagenType
		{
			public string name;
			public MetagenField[] fields;
		}

		private sealed class MetagenTable
		{
			public string stringID;
			public string itemClass;
			public MetagenTableField[] fields;
		}

		private sealed class MetagenTableField
		{
			public string id;
			public string name;
			public string type;
			public bool isAttr;
		}

		private sealed class MetagenMergeableRequest
		{
			public string messageType;
		}

		private sealed class MetagenUserAttribute
		{
			public string stringID;
			public string type;
			public string name;
			public string clientRead;
			public string clientWrite;
		}

		#endregion
	}
}
