using System;
using System.Collections.Generic;
using System.Text;
using Debug = UnityEngine.Debug;

namespace MiniIT.Snipe.Unity.Editor
{
	/// <summary>
	/// Generates a strongly-typed <c>SnipeApiService.cs</c> bindings file from API specs JSON
	/// that mirrors the server-side API.
	/// </summary>
	public static class SnipeApiGenerator
	{
		/// <summary>
		/// Generates C# code from the provided specs JSON string.
		/// </summary>
		/// <param name="specsJson">The API specs JSON string.</param>
		/// <returns>The generated C# code as a string, or null if generation failed.</returns>
		public static string Generate(string specsJson)
		{
			if (string.IsNullOrEmpty(specsJson))
			{
				Debug.LogError("SnipeApiGenerator.Generate - specsJson is null or empty");
				return null;
			}

			try
			{
				var root = ParseJson(specsJson);
				if (root == null)
				{
					Debug.LogError("SnipeApiGenerator.Generate - failed to parse specs JSON");
					return null;
				}

				string code = GenerateCode(root);
				Debug.Log($"SnipeApiGenerator.Generate - successfully generated code ({code.Length} characters)");
				return code;
			}
			catch (Exception e)
			{
				Debug.LogError($"SnipeApiGenerator.Generate - exception while generating: {e}");
				return null;
			}
		}

		#region Code generation

		private static string GenerateCode(MetagenRoot root)
		{
			var sb = new StringBuilder(64 * 1024);

			GenerateFileHeader(sb, root);
			GenerateNamespaceOpen(sb);
			GenerateContextFactory(sb, root);
			GenerateExtensions(sb);
			GenerateServiceClass(sb, root);
			GenerateModules(sb, root);
			GenerateTypes(sb, root);
			GenerateUserAttributes(sb, root);
			GenerateTables(sb, root);
			GenerateNamespaceClose(sb);

			return sb.ToString();
		}

		private static void GenerateFileHeader(StringBuilder sb, MetagenRoot root)
		{
			string projectId = string.IsNullOrEmpty(root.projectStringID) ? root.projectID.ToString() : root.projectStringID;
			string version = string.IsNullOrEmpty(root.snipeVersion) ? "8.0" : root.snipeVersion;

			if (!DateTime.TryParse(root.generatedAt, out DateTime generatedAt))
			{
				generatedAt = DateTime.Now;
			}

			sb.AppendLine("// <auto-generated />");
			sb.Append("// Snipe Api v").Append(version)
				.Append(" for project ").Append(projectId)
				.Append(", ").AppendLine(generatedAt.ToUniversalTime().ToString("dd MMM yyyy, HH:mm:ss UTC"));
			sb.AppendLine("// THIS FILE IS AUTO-GENERATED. ALL EDITS WILL BE LOST.");
			sb.AppendLine();
			sb.AppendLine("using System;");
			sb.AppendLine("using System.Collections.Generic;");
			sb.AppendLine("using System.Collections;");
			sb.AppendLine("using MiniIT.Snipe.Configuration;");
			sb.AppendLine("using MiniIT.Threading;");
			sb.AppendLine();
		}

		private static void GenerateNamespaceOpen(StringBuilder sb)
		{
			sb.AppendLine("namespace MiniIT.Snipe.Api");
			sb.AppendLine("{");
		}

		private static void GenerateNamespaceClose(StringBuilder sb)
		{
			sb.AppendLine("}");
		}

		private static void GenerateContextFactory(StringBuilder sb, MetagenRoot root)
		{
			Indent(sb, 1).AppendLine("public sealed class SnipeApiContextFactory : AbstractSnipeApiContextFactory, ISnipeContextAndTablesFactory");
			Indent(sb, 1).AppendLine("{");
			Indent(sb, 2).AppendLine("public SnipeApiContextFactory(ISnipeManager tablesProvider, SnipeConfigBuilder configBuilder)");
			Indent(sb, 3).AppendLine(": base(tablesProvider, configBuilder) { }");
			sb.AppendLine();

			// Parse timezone from spec (format: "+0300" or "-0500")
			double timezoneHours = 3.0; // default
			if (!string.IsNullOrEmpty(root.timeZone))
			{
				if (root.timeZone.StartsWith("+") || root.timeZone.StartsWith("-"))
				{
					string sign = root.timeZone.Substring(0, 1);
					string hoursStr = root.timeZone.Substring(1, 2);
					string minutesStr = root.timeZone.Length > 3 ? root.timeZone.Substring(3, 2) : "00";
					if (int.TryParse(hoursStr, out int hours) && int.TryParse(minutesStr, out int minutes))
					{
						timezoneHours = hours + (minutes / 60.0);
						if (sign == "-")
							timezoneHours = -timezoneHours;
					}
				}
			}

			Indent(sb, 2).Append("public override TimeSpan GetServerTimeZoneOffset() => TimeSpan.FromHours(")
				.Append(timezoneHours.ToString("F1", System.Globalization.CultureInfo.InvariantCulture)).AppendLine(");");
			Indent(sb, 2).AppendLine("public override AbstractSnipeApiService CreateSnipeApiService(SnipeCommunicator communicator, AuthSubsystem auth) => new SnipeApiService(communicator, auth);");
			Indent(sb, 2).AppendLine("public SnipeApiTables CreateSnipeApiTables() => new SnipeTables();");
			Indent(sb, 1).AppendLine("}");
			sb.AppendLine();
		}

		private static void GenerateExtensions(StringBuilder sb)
		{
			Indent(sb, 1).AppendLine("public static class SnipeApiExtensions");
			Indent(sb, 1).AppendLine("{");
			Indent(sb, 2).AppendLine("public static SnipeApiService GetApi(this SnipeContext context) => (SnipeApiService)(context as SnipeApiContext).GetSnipeApiService();");
			Indent(sb, 2).AppendLine("public static SnipeTables GetTables(this ISnipeTablesProvider tablesProvider) => (SnipeTables)tablesProvider.GetSnipeTables();");
			Indent(sb, 1).AppendLine("}");
			sb.AppendLine();
		}

		private static void GenerateServiceClass(StringBuilder sb, MetagenRoot root)
		{
			Indent(sb, 1).AppendLine("public sealed class SnipeApiService : AbstractSnipeApiService");
			Indent(sb, 1).AppendLine("{");

			// Module properties
			if (root.modules != null)
			{
				foreach (var module in root.modules)
				{
					if (string.IsNullOrEmpty(module.name))
						continue;

					string moduleClass = "SnipeApiModule" + module.name;
					Indent(sb, 2).Append("public ").Append(moduleClass).Append(' ').Append(module.name).Append(" { get; }").AppendLine();
				}
			}

			sb.AppendLine();
			Indent(sb, 2).AppendLine("public SnipeApiService(SnipeCommunicator communicator, AuthSubsystem auth)");
			Indent(sb, 2).AppendLine("\t: base(communicator, auth)");
			Indent(sb, 2).AppendLine("{");

			if (root.modules != null)
			{
				foreach (var module in root.modules)
				{
					if (string.IsNullOrEmpty(module.name))
						continue;

					string moduleClass = "SnipeApiModule" + module.name;
					Indent(sb, 3).Append(module.name).Append(" = new ").Append(moduleClass).AppendLine("(this);");
				}
			}

			Indent(sb, 2).AppendLine("}");
			sb.AppendLine();

			// Mergeable requests
			Indent(sb, 2).AppendLine("protected override void InitMergeableRequestTypes()");
			Indent(sb, 2).AppendLine("{");

			if (root.mergeableRequests != null)
			{
				foreach (var mr in root.mergeableRequests)
				{
					if (string.IsNullOrEmpty(mr.messageType))
						continue;

					if (mr.payload != null && mr.payload.Count > 0)
					{
						Indent(sb, 3).Append("AddMergeableRequestType(new SnipeRequestDescriptor() { MessageType = \"")
							.Append(mr.messageType).Append("\", Data = new Dictionary<string, object>() { ");

						bool first = true;
						foreach (KeyValuePair<string, string> pair in mr.payload)
						{
							if (!first)
							{
								sb.Append(", ");
							}
							first = false;

							sb.Append("[\"").Append(pair.Key).Append("\"] = \"").Append(pair.Value).Append('\"');
						}

						sb.AppendLine(" } });");
					}
					else
					{
						Indent(sb, 3).Append("AddMergeableRequestType(\"").Append(mr.messageType).AppendLine("\");");
					}
				}
			}

			Indent(sb, 2).AppendLine("}");
			Indent(sb, 1).AppendLine("}");
			sb.AppendLine();
		}

		private static void GenerateModules(StringBuilder sb, MetagenRoot root)
		{
			if (root.modules == null)
				return;

			foreach (var module in root.modules)
			{
				if (string.IsNullOrEmpty(module.name))
					continue;

				string moduleClass = "SnipeApiModule" + module.name;
				bool isUserAttr = module.name == "UserAttr";
				bool isGameVars = module.name == "Vars";

				Indent(sb, 1).Append("public sealed class ").Append(moduleClass).AppendLine(" : SnipeApiModule");
				Indent(sb, 1).AppendLine("{");

				// Special properties for UserAttr module
				if (isUserAttr)
				{
					Indent(sb, 2).AppendLine("public UserAttributes UserAttributes { get; private set; }");
					Indent(sb, 2).AppendLine("public bool Initialized { get; private set; }");
					sb.AppendLine();
				}

				// Special properties for Vars module (strongly-typed Game Variables cache)
				if (isGameVars && root.gameVars != null && root.gameVars.Length > 0)
				{
					foreach (var gv in root.gameVars)
					{
						if (gv == null || string.IsNullOrEmpty(gv.property))
							continue;

						string csType = MapTypeToCs(!string.IsNullOrEmpty(gv.resolvedType) ? gv.resolvedType : gv.type, null);
						Indent(sb, 2).Append("public ").Append(csType).Append(' ').Append(gv.property).AppendLine(" { get; private set; }");
					}
					sb.AppendLine();
				}

				Indent(sb, 2).Append("internal ").Append(moduleClass).AppendLine("(SnipeApiService snipeApiService) : base(snipeApiService)");
				Indent(sb, 2).AppendLine("{");

				// Special initialization for UserAttr module
				if (isUserAttr)
				{
					Indent(sb, 3).AppendLine("UserAttributes = new UserAttributes(snipeApiService);");
				}

				bool hasResponses = module.responses != null && module.responses.Length > 0;
				if (hasResponses)
				{
					Indent(sb, 3).AppendLine("SubscribeOnMessageReceived(OnMessageReceived);");
				}

				Indent(sb, 2).AppendLine("}");
				sb.AppendLine();

				// Methods
				if (module.methods != null)
				{
					foreach (var method in module.methods)
					{
						GenerateMethod(sb, method, isGameVars ? root.gameVars : null, isGameVars);
					}
				}

				// Responses -> events
				if (module.responses != null && module.responses.Length > 0)
				{
					foreach (var response in module.responses)
					{
						GenerateResponseEvent(sb, response);
					}

					GenerateOnMessageReceived(sb, module);
				}

				Indent(sb, 1).AppendLine("}");
				sb.AppendLine();
			}
		}

		private static void GenerateMethod(StringBuilder sb, MetagenMethod method)
		{
			GenerateMethod(sb, method, null, false);
		}

		private static void GenerateMethod(StringBuilder sb, MetagenMethod method, MetagenGameVar[] gameVars, bool isGameVarsModule)
		{
			if (method == null || string.IsNullOrEmpty(method.callName) || string.IsNullOrEmpty(method.messageType))
				return;

			string methodName = ExtractMethodName(method);
			string callbackName = methodName + "Callback";

			// Delegate
			Indent(sb, 2).Append("public delegate void ").Append(callbackName).Append("(");

			if (method.outputs == null || method.outputs.Length == 0)
			{
				sb.Append("string errorCode");
			}
			else
			{
				bool first = true;
				foreach (var field in method.outputs)
				{
					// Skip errorCode in outputs since it's always the first parameter
					// if (field.name == "errorCode")
					// 	continue;

					if (!first)
					{
						sb.AppendLine(",");
						Indent(sb, 3);
					}
					first = false;

					string csType = MapTypeToCs(field.type, field.itemType);
					sb.Append(csType).Append(' ').Append(field.name);
				}
			}

			sb.AppendLine(");").AppendLine();

			// XML doc with inputs, outputs, and error codes
			EmitMethodSummary(sb, method);

			// Method signature
			Indent(sb, 2).Append("public bool ").Append(methodName).Append("(");

			// inputs as parameters
			bool firstParam = true;
			if (method.inputs != null)
			{
				foreach (var field in method.inputs)
				{
					if (!firstParam)
					{
						sb.Append(", ");
					}
					firstParam = false;

					string csType = MapTypeToCs(field.type, field.itemType);
					sb.Append(csType).Append(' ').Append(field.name);
				}
			}

			if (!firstParam)
			{
				sb.Append(", ");
			}

			sb.Append(callbackName).AppendLine(" callback = null)");
			Indent(sb, 2).AppendLine("{");

			bool hasInputs = method.inputs != null && method.inputs.Length > 0;

			// requestData dictionary
			Indent(sb, 3).AppendLine("var requestData = new Dictionary<string, object>()");
			Indent(sb, 3).AppendLine("{");

			if (!string.IsNullOrEmpty(method.actionID))
			{
				Indent(sb, 4).Append("[\"actionID\"] = \"").Append(method.actionID).Append('\"')
					.AppendLine(hasInputs && method.inputs.Length > 0 ? "," : string.Empty);
			}

			if (hasInputs)
			{
				for (int i = 0; i < method.inputs.Length; i++)
				{
					var field = method.inputs[i];
					Indent(sb, 4).Append("[\"").Append(field.name).Append("\"] = ").Append(field.name)
						.AppendLine(i < method.inputs.Length - 1 ? "," : string.Empty);
				}
			}

			Indent(sb, 3).AppendLine("};");

			// CreateRequest
			Indent(sb, 3).AppendLine($"var request = CreateRequest(\"{method.messageType}\", requestData);");
			Indent(sb, 3).AppendLine("if (request == null)");
			Indent(sb, 4).AppendLine("return false;");
			sb.AppendLine();

			// Request callback - special handling for UserAttr.GetAll
			bool isUserAttrGetAll = method.messageType == "attr.getAll";
			bool isVarsGetAll = isGameVarsModule
				&& string.Equals(methodName, "GetAll", StringComparison.Ordinal)
				&& method.outputs != null
				&& HasFieldNamed(method.outputs, "data")
				&& gameVars != null
				&& gameVars.Length > 0;

			if (isUserAttrGetAll)
			{
				Indent(sb, 3).AppendLine("request.Request(async (errorCode, responseData) =>");
				Indent(sb, 3).AppendLine("{");
				Indent(sb, 4).AppendLine("this.Initialized = true;");
				Indent(sb, 4).AppendLine("await AlterTask.Yield();");
				Indent(sb, 4).AppendLine("callback?.Invoke(errorCode, this.UserAttributes);");
			}
			else if (isVarsGetAll)
			{
				Indent(sb, 3).AppendLine("request.Request((errorCode, responseData) =>");
				Indent(sb, 3).AppendLine("{");

				// Build GameVariable list from responseData["data"]
				Indent(sb, 4).AppendLine("var o_data = new List<GameVariable>();");
				Indent(sb, 4).AppendLine("if (responseData.TryGetValue(\"data\", out var d) && d is IList src_data)");
				Indent(sb, 4).AppendLine("{");
				Indent(sb, 5).AppendLine("foreach (Dictionary<string, object> o in src_data)");
				Indent(sb, 5).AppendLine("{");
				Indent(sb, 6).AppendLine("var tmp = new GameVariable(o);");
				Indent(sb, 6).AppendLine("o_data.Add(tmp);");

				// Populate strongly-typed cache fields from tmp.key/tmp.val
				foreach (var gv in gameVars)
				{
					if (gv == null || string.IsNullOrEmpty(gv.stringID) || string.IsNullOrEmpty(gv.property))
						continue;

					string csType = MapTypeToCs(!string.IsNullOrEmpty(gv.resolvedType) ? gv.resolvedType : gv.type, null);
					EmitGameVarAssignment(sb, gv.stringID, gv.property, csType, 6);
				}

				Indent(sb, 5).AppendLine("}");
				Indent(sb, 4).AppendLine("}");

				// Extract other outputs (if any) + invoke callback
				foreach (var field in method.outputs)
				{
					if (field.name == "errorCode" || field.name == "data")
						continue;
					GenerateOutputFieldExtraction(sb, field, 4);
				}

				Indent(sb, 4).Append("callback?.Invoke(errorCode");
				foreach (var field in method.outputs)
				{
					if (field.name == "errorCode")
						continue;

					if (field.name == "data")
						sb.Append(", o_data");
					else
						sb.Append(", ").Append(field.name);
				}
				sb.AppendLine(");");
			}
			else
			{
				Indent(sb, 3).AppendLine("request.Request((errorCode, responseData) =>");
				Indent(sb, 3).AppendLine("{");

				if (method.outputs != null && method.outputs.Length > 0)
				{
					foreach (var field in method.outputs)
					{
						// Skip errorCode in outputs since it's always the first parameter
						if (field.name == "errorCode")
							continue;
						GenerateOutputFieldExtraction(sb, field, 4);
					}

					Indent(sb, 4).Append("callback?.Invoke(errorCode");
					foreach (var field in method.outputs)
					{
						// Skip errorCode in outputs since it's always the first parameter
						if (field.name == "errorCode")
							continue;

						string paramName = (method.messageType == "attr.getAll" && field.name == "data")
							? "this.UserAttributes"
							: field.name;
						sb.Append(", ").Append(paramName);
					}
					sb.AppendLine(");");
				}
				else
				{
					Indent(sb, 4).AppendLine("callback?.Invoke(errorCode);");
				}
			}

			Indent(sb, 3).AppendLine("});");
			Indent(sb, 3).AppendLine("return true;");
			Indent(sb, 2).AppendLine("}");
			sb.AppendLine();
		}

		private static bool HasFieldNamed(MetagenField[] fields, string name)
		{
			if (fields == null)
				return false;
			for (int i = 0; i < fields.Length; i++)
			{
				if (fields[i] != null && fields[i].name == name)
					return true;
			}
			return false;
		}

		private static void EmitGameVarAssignment(StringBuilder sb, string stringId, string propertyName, string csType, int indent)
		{
			Indent(sb, indent).Append("if (tmp.key == \"").Append(stringId).AppendLine("\")");
			Indent(sb, indent).AppendLine("{");

			if (csType.StartsWith("List<", StringComparison.Ordinal) && csType.EndsWith(">", StringComparison.Ordinal))
			{
				string itemType = GetArrayItemType(csType);
				string srcName = "src_" + propertyName;
				string itemVar = "o_" + propertyName;

				Indent(sb, indent + 1).Append(propertyName).Append(" = new ").Append(csType).AppendLine("();");
				Indent(sb, indent + 1).Append("if (tmp.val is IList ").Append(srcName).AppendLine(")");
				Indent(sb, indent + 1).AppendLine("{");
				Indent(sb, indent + 2).Append("foreach (var ").Append(itemVar).Append(" in ").Append(srcName).AppendLine(")");
				Indent(sb, indent + 2).AppendLine("{");

				if (itemType == "int")
				{
					Indent(sb, indent + 3).Append(propertyName).Append(".Add(Convert.ToInt32(").Append(itemVar).AppendLine("));");
				}
				else if (itemType == "float")
				{
					Indent(sb, indent + 3).Append(propertyName).Append(".Add(Convert.ToSingle(").Append(itemVar).AppendLine("));");
				}
				else if (itemType == "bool")
				{
					Indent(sb, indent + 3).Append(propertyName).Append(".Add(Convert.ToBoolean(").Append(itemVar).AppendLine("));");
				}
				else if (itemType == "string")
				{
					Indent(sb, indent + 3).Append(propertyName).Append(".Add(").Append(itemVar).AppendLine("?.ToString());");
				}
				else if (itemType == "object")
				{
					Indent(sb, indent + 3).Append(propertyName).Append(".Add(").Append(itemVar).AppendLine(");");
				}
				else
				{
					// custom element type
					Indent(sb, indent + 3).Append("if (").Append(itemVar).Append(" is Dictionary<string, object> map_").Append(propertyName).AppendLine(")");
					Indent(sb, indent + 3).AppendLine("{");
					Indent(sb, indent + 4).Append(propertyName).Append(".Add(new ").Append(itemType).Append("(map_").Append(propertyName).AppendLine("));");
					Indent(sb, indent + 3).AppendLine("}");
				}

				Indent(sb, indent + 2).AppendLine("}");
				Indent(sb, indent + 1).AppendLine("}");
			}
			else if (csType == "int")
			{
				Indent(sb, indent + 1).Append(propertyName).AppendLine(" = Convert.ToInt32(tmp.val);");
			}
			else if (csType == "float")
			{
				Indent(sb, indent + 1).Append(propertyName).AppendLine(" = Convert.ToSingle(tmp.val);");
			}
			else if (csType == "bool")
			{
				Indent(sb, indent + 1).Append(propertyName).AppendLine(" = Convert.ToBoolean(tmp.val);");
			}
			else if (csType == "string")
			{
				Indent(sb, indent + 1).Append(propertyName).AppendLine(" = tmp.val?.ToString();");
			}
			else if (csType == "object")
			{
				Indent(sb, indent + 1).Append(propertyName).AppendLine(" = tmp.val;");
			}
			else
			{
				// custom type / json object – try dictionary-based
				Indent(sb, indent + 1).Append(propertyName).Append(" = new ").Append(csType).AppendLine("(tmp.val as Dictionary<string, object>);");
			}

			Indent(sb, indent).AppendLine("}");
		}

		private static string ExtractMethodName(MetagenMethod method)
		{
			if (!string.IsNullOrEmpty(method.actionID))
			{
				// Extract method name from actionID: "car.insertMaterial" -> "CarInsertMaterial", "debug.resetUser" -> "DebugResetUser"
				string[] parts = method.actionID.Split('.');
				string actionName = "";
				foreach (string part in parts)
				{
					actionName += char.ToUpperInvariant(part[0]) + part.Substring(1);
				}
				return actionName;
			}

			// Extract method name from messageType: "attr.getAll" -> "GetAll", "attr.getMulti" -> "GetMulti"
			// Split by '.' and take the right part, then capitalize first letter
			string methodName = method.messageType;
			int dotIndex = methodName.IndexOf('.');
			if (dotIndex >= 0 && dotIndex < methodName.Length - 1)
			{
				methodName = methodName.Substring(dotIndex + 1);
				if (methodName.Length > 0)
				{
					methodName = char.ToUpperInvariant(methodName[0]) + methodName.Substring(1);
				}
			}
			return methodName;
		}

		/// <summary>
		/// XML doc with inputs, outputs, and error codes - standard XML doc format
		/// </summary>
		private static void EmitMethodSummary(StringBuilder sb, MetagenMethod method)
		{
			Indent(sb, 2).AppendLine("/// <summary>");
			Indent(sb, 2).Append("/// __").Append(method.messageType).AppendLine("__");

			// Description from doc - combine into paragraphs
			if (method.doc != null && method.doc.Length > 0)
			{
				var descriptionBuilder = new StringBuilder();
				foreach (var line in method.doc)
				{
					if (string.IsNullOrWhiteSpace(line))
					{
						if (descriptionBuilder.Length > 0)
						{
							Indent(sb, 2).Append("/// <para>").Append(EscapeXml(descriptionBuilder.ToString().Trim())).AppendLine("</para>");
							descriptionBuilder.Clear();
						}
					}
					else
					{
						if (descriptionBuilder.Length > 0)
							descriptionBuilder.Append(" ");
						descriptionBuilder.Append(line.Trim());
					}
				}
				if (descriptionBuilder.Length > 0)
				{
					Indent(sb, 2).Append("/// <para>").Append(EscapeXml(descriptionBuilder.ToString().Trim())).AppendLine("</para>");
				}
			}

			// Input section
			if (method.inputs != null && method.inputs.Length > 0)
			{
				Indent(sb, 2).AppendLine("/// Input:<ul>");
				foreach (var field in method.inputs)
				{
					string optional = field.optional ? " (optional)" : "";
					string csType = MapTypeToCs(field.type, field.itemType);
					string typeName = GetTypeDisplayName(csType);
					string desc = !string.IsNullOrEmpty(field.description) ? ". " + field.description : "";
					Indent(sb, 2).Append("/// <li>`").Append(field.name).Append("`").Append(optional)
						.Append(" - `").Append(typeName).Append("`").Append(desc).AppendLine("</li>");
				}
				Indent(sb, 2).AppendLine("/// </ul><br/>");
			}

			// Output section
			if (method.outputs != null && method.outputs.Length > 0)
			{
				Indent(sb, 2).AppendLine("/// Output:<ul>");
				foreach (var field in method.outputs)
				{
					string csType = MapTypeToCs(field.type, field.itemType);
					string typeName = GetTypeDisplayName(csType);
					string desc = !string.IsNullOrEmpty(field.description) ? ". " + field.description : "";
					Indent(sb, 2).Append("/// <li>`").Append(field.name).Append("` - `").Append(typeName)
						.Append("`").Append(desc).AppendLine("</li>");
				}
				Indent(sb, 2).AppendLine("/// </ul><br/>");
			}

			// Error codes section
			if (method.errorCodes != null && method.errorCodes.Length > 0)
			{
				Indent(sb, 2).AppendLine("/// Error codes:<ul>");
				foreach (var errorCode in method.errorCodes)
				{
					if (string.IsNullOrWhiteSpace(errorCode))
						continue;
					Indent(sb, 2).Append("/// <li>").Append(EscapeXml(errorCode)).AppendLine("</li>");
				}
				Indent(sb, 2).AppendLine("/// </ul><br/>");
			}
			Indent(sb, 2).AppendLine("/// </summary>");
		}

		private static void GenerateOutputFieldExtraction(StringBuilder sb, MetagenField field, int indent)
		{
			string csType = MapTypeToCs(field.type, field.itemType);
			string varName = field.name;

			if (field.type == "string")
			{
				Indent(sb, indent).Append(csType).Append(' ').Append(varName)
					.Append(" = responseData.SafeGetString(\"").Append(field.name).AppendLine("\");");
			}
			else if (field.type == "int" || field.type == "float" || field.type == "boolean")
			{
				string genericType = csType == "bool" ? "bool" : csType;
				Indent(sb, indent).Append(csType).Append(' ').Append(varName)
					.Append(" = responseData.SafeGetValue<").Append(genericType).Append(">(\"")
					.Append(field.name).AppendLine("\");");
			}
			else if (field.type == "array")
			{
				string listVarName = field.name + "List";

				Indent(sb, indent).Append("var ").Append(varName).Append(" = new ").Append(csType).AppendLine("();");
				Indent(sb, indent).AppendLine($"if (responseData.TryGetValue(\"{field.name}\", out var {listVarName}) && {listVarName} is IList src_{field.name})");
				Indent(sb, indent).AppendLine("{");

				// assume arrays of simple dictionaries / scalars; keep generic
				Indent(sb, indent + 1).Append("foreach (var o in src_").Append(field.name).Append(')').AppendLine();
				Indent(sb, indent + 2).Append(varName).Append(".Add((").Append(GetArrayItemType(csType))
					.AppendLine(")o);");

				Indent(sb, indent).AppendLine("}");
			}
			else if (field.type == "Dynamic")
			{
				Indent(sb, indent).Append(csType).Append(' ').Append(varName)
					.Append(" = responseData[\"").Append(field.name).AppendLine("\"];");
			}
			else
			{
				// custom type / json object – try dictionary-based
				Indent(sb, indent).Append(csType).Append(' ').Append(varName)
					.Append(" = new ").Append(csType)
					.Append("(responseData[\"").Append(field.name).Append("\"] as Dictionary<string, object>);")
					.AppendLine();
			}
		}

		private static string GetArrayItemType(string listType)
		{
			int start = listType.IndexOf('<');
			int end = listType.LastIndexOf('>');
			if (start >= 0 && end > start)
				return listType.Substring(start + 1, end - start - 1);
			return "object";
		}

		private static void GenerateResponseEvent(StringBuilder sb, MetagenResponse response, string obsoleteMessageCallName = null)
		{
			if (response == null || string.IsNullOrEmpty(response.msgType) || string.IsNullOrEmpty(response.callName))
				return;

			string handlerName = response.callName + "Handler";
			string eventName = "On" + response.callName;

			if (obsoleteMessageCallName != null)
			{
				string obsoleteHandlerName = obsoleteMessageCallName + "Handler";
				Indent(sb, 2).AppendLine($"[Obsolete(\"Use {obsoleteHandlerName} instead\")]");
			}

			Indent(sb, 2).Append("public delegate void ").Append(handlerName).AppendLine("(");


			if (response.fields != null)
			{
				bool first = true;
				foreach (var field in response.fields)
				{
					if (!first)
					{
						Indent(sb, 0).AppendLine(",");
					}
					first = false;

					string csType = MapTypeToCs(field.type, field.itemType);
					Indent(sb, 3).Append(csType).Append(' ').Append(field.name);
				}
			}

			sb.AppendLine(");");

			if (obsoleteMessageCallName != null)
			{
				string obsoleteEventName = "On" + obsoleteMessageCallName;
				Indent(sb, 2).AppendLine($"[Obsolete(\"Use {obsoleteEventName} instead\")]");
			}

			Indent(sb, 2).Append("public event ").Append(handlerName).Append(' ').Append(eventName).AppendLine(";")
				.AppendLine();

			// Legacy
			if (obsoleteMessageCallName != null)
			{
				return;
			}
			if (response.msgType is "chat.msg" or "clan.msg")
			{
				string msgType = response.msgType;
				string callName = response.callName;
				response.msgType += ".legacy";
				response.callName = "Msg";
				GenerateResponseEvent(sb, response, callName);

				// Restore values for later use
				response.msgType = msgType;
				response.callName = callName;
			}
		}

		private static void GenerateOnMessageReceived(StringBuilder sb, MetagenModule module)
		{
			Indent(sb, 2).AppendLine("private void OnMessageReceived(string messageType, string errorCode, IDictionary<string, object> responseData, int requestId)");
			Indent(sb, 2).AppendLine("{");

			bool first = true;
			foreach (var response in module.responses)
			{
				if (response == null || string.IsNullOrEmpty(response.msgType) || string.IsNullOrEmpty(response.callName))
					continue;

				string eventName = "On" + response.callName;

				Indent(sb, 3).Append(first ? "if" : "else if").Append(" (messageType == \"")
					.Append(response.msgType).AppendLine("\")");
				Indent(sb, 3).AppendLine("{");

				if (response.fields != null && response.fields.Length > 0)
				{
					foreach (var field in response.fields)
					{
						// Skip errorCode since we already have it as a parameter
						if (field.name == "errorCode")
							continue;

						GenerateOutputFieldExtraction(sb, field, 4);
					}

					Indent(sb, 4).Append(eventName).Append("?.Invoke(");
					bool firstParam = true;
					foreach (var field in response.fields)
					{
						if (!firstParam)
						{
							sb.Append(", ");
						}
						firstParam = false;

						sb.Append(field.name);
					}
					sb.AppendLine(");");

					// Legacy
					if (response.msgType is "chat.msg" or "clan.msg")
					{
						Indent(sb, 4).Append("OnMsg").Append("?.Invoke(");
						firstParam = true;
						foreach (var field in response.fields)
						{
							if (!firstParam)
							{
								sb.Append(", ");
							}
							firstParam = false;

							sb.Append(field.name);
						}
						sb.AppendLine(");");
					}
				}
				else
				{
					Indent(sb, 4).Append(eventName).AppendLine("?.Invoke(errorCode);");

					// Legacy
					if (response.msgType is "chat.msg" or "clan.msg")
					{
						Indent(sb, 4).Append("OnMsg").AppendLine("?.Invoke(errorCode);");
					}
				}

				Indent(sb, 3).AppendLine("}");

				first = false;
			}

			Indent(sb, 2).AppendLine("}");
		}

		private static void GenerateTypes(StringBuilder sb, MetagenRoot root)
		{
			if (root.types == null)
				return;

			foreach (var type in root.types)
			{
				if (string.IsNullOrEmpty(type.name))
					continue;

				Indent(sb, 1).AppendLine("[System.Serializable]");
				Indent(sb, 1).Append("public sealed class ").Append(type.name).AppendLine(" : IMapConvertible");
				Indent(sb, 1).AppendLine("{");

				// fields
				if (type.fields != null)
				{
					foreach (var field in type.fields)
					{
						string csType = MapTypeToCs(field.type, field.itemType);
						Indent(sb, 2).Append("public ").Append(csType).Append(' ').Append(field.name).AppendLine(";");
					}
				}

				// default ctor
				Indent(sb, 2).Append("public ").Append(type.name).AppendLine("() {}");

				// ctor from map
				Indent(sb, 2).Append("public ").Append(type.name).AppendLine("(IDictionary<string, object> data = null)");
				Indent(sb, 2).AppendLine("{");
				Indent(sb, 3).AppendLine("if (data == null) return;");

				if (type.fields != null)
				{
					foreach (var field in type.fields)
					{
						var csType = MapTypeToCs(field.type, field.itemType);

						if (field.type == "string")
						{
							Indent(sb, 3).Append("this.").Append(field.name).Append(" = data.SafeGetString(\"")
								.Append(field.name).AppendLine("\");");
						}
						else if (field.type == "int" || field.type == "float" || field.type == "boolean")
						{
							string genericType = csType == "bool" ? "bool" : csType;
							Indent(sb, 3).Append("this.").Append(field.name).Append(" = data.SafeGetValue<")
								.Append(genericType).Append(">(\"").Append(field.name).AppendLine("\");");
						}
						else if (field.type == "array")
						{
							string listType = csType;
							string itemType = GetArrayItemType(listType);
							string listVarName = field.name + "List";

							Indent(sb, 3).Append("var ").Append(field.name).Append(" = new ").Append(listType).AppendLine("();");
							Indent(sb, 3).AppendLine($"if (data.TryGetValue(\"{field.name}\", out var {listVarName}) && {listVarName} is IList src_{field.name})");
							Indent(sb, 3).AppendLine("{");
							Indent(sb, 4).Append("foreach (").Append(itemType).Append(" o in src_").Append(field.name).AppendLine(")");
							Indent(sb, 5).Append(field.name).AppendLine(".Add(o);");
							Indent(sb, 3).AppendLine("}");
							Indent(sb, 3).Append("this.").Append(field.name).Append(" = ").Append(field.name).AppendLine(";");
						}
						else if (field.type == "Dynamic")
						{
							Indent(sb, 3).Append("this.").Append(field.name)
								.Append(" = data[\"").Append(field.name).AppendLine("\"];");
						}
						else
						{
							Indent(sb, 3).Append("this.").Append(field.name).Append(" = new ").Append(csType)
								.Append("(data[\"").Append(field.name).Append("\"] as Dictionary<string, object>);")
								.AppendLine();
						}
					}
				}

				Indent(sb, 2).AppendLine("}");
				sb.AppendLine();

				// implicit operator
				Indent(sb, 2).Append("public static implicit operator ").Append(type.name)
					.AppendLine("(Dictionary<string, object> data)");
				Indent(sb, 2).AppendLine("{");
				Indent(sb, 3).Append("return new ").Append(type.name).AppendLine("(data);");
				Indent(sb, 2).AppendLine("}");
				sb.AppendLine();

				// ToMap
				Indent(sb, 2).AppendLine("public IDictionary<string, object> ToMap()");
				Indent(sb, 2).AppendLine("{");
				Indent(sb, 3).AppendLine("return new Dictionary<string, object>()");
				Indent(sb, 3).AppendLine("{");

				if (type.fields != null)
				{
					for (int i = 0; i < type.fields.Length; i++)
					{
						var field = type.fields[i];
						Indent(sb, 4).Append("[\"").Append(field.name).Append("\"] = this.").Append(field.name);
						sb.AppendLine(i < type.fields.Length - 1 ? "," : string.Empty);
					}
				}

				Indent(sb, 3).AppendLine("};");
				Indent(sb, 2).AppendLine("}");
				Indent(sb, 1).AppendLine("}");
				sb.AppendLine();
			}
		}

		private static void GenerateUserAttributes(StringBuilder sb, MetagenRoot root)
		{
			if (root.userAttributes == null || root.userAttributes.Length == 0)
				return;

			Indent(sb, 1).AppendLine("public sealed class UserAttributes : SnipeApiUserAttributes");
			Indent(sb, 1).AppendLine("{");

			foreach (var attr in root.userAttributes)
			{
				if (string.IsNullOrEmpty(attr.stringID))
					continue;

				string csType = MapTypeToCs(attr.type, null);
				bool isReadOnly = attr.clientWrite == "internal" || attr.clientWrite == "none";
				string attributeType = isReadOnly ? $"SnipeApiReadOnlyUserAttribute<{csType}>" : $"SnipeApiUserAttribute<{csType}>";
				Indent(sb, 2).Append("public ").Append(attributeType).Append(' ').Append(attr.stringID).AppendLine(" { get; }");
			}

			sb.AppendLine();
			Indent(sb, 2).AppendLine("public UserAttributes(SnipeApiService snipeApiService) : base(snipeApiService)");
			Indent(sb, 2).AppendLine("{");

			foreach (var attr in root.userAttributes)
			{
				if (string.IsNullOrEmpty(attr.stringID))
					continue;

				string csType = MapTypeToCs(attr.type, null);
				bool isReadOnly = attr.clientWrite == "internal" || attr.clientWrite == "none";
				string attributeType = isReadOnly ? $"SnipeApiReadOnlyUserAttribute<{csType}>" : $"SnipeApiUserAttribute<{csType}>";
				Indent(sb, 3).Append(attr.stringID).Append(" = RegisterAttribute(new ").Append(attributeType)
					.Append("(snipeApiService, \"").Append(attr.stringID).AppendLine("\"));");
			}

			Indent(sb, 2).AppendLine("}");
			Indent(sb, 1).AppendLine("}");
			sb.AppendLine();
		}

		private static void GenerateTables(StringBuilder sb, MetagenRoot root)
		{
			if (root.tables == null || root.tables.Length == 0)
				return;

			// SnipeTables
			Indent(sb, 1).AppendLine("public sealed class SnipeTables : SnipeApiTables");
			Indent(sb, 1).AppendLine("{");

			foreach (var table in root.tables)
			{
				if (string.IsNullOrEmpty(table.stringID))
					continue;

				string itemClassName = string.IsNullOrEmpty(table.itemClass) ? "SnipeTable" + table.stringID + "Item" : table.itemClass;
				Indent(sb, 2).Append("public SnipeTable<").Append(itemClassName).Append("> ").Append(table.stringID)
					.AppendLine(" { get; }");
			}

			sb.AppendLine();
			Indent(sb, 2).AppendLine("public SnipeTables()");
			Indent(sb, 2).AppendLine("{");

			foreach (var table in root.tables)
			{
				if (string.IsNullOrEmpty(table.stringID))
					continue;

				string itemClassName = string.IsNullOrEmpty(table.itemClass) ? "SnipeTable" + table.stringID + "Item" : table.itemClass;
				Indent(sb, 3).Append(table.stringID).Append(" = RegisterTable(new SnipeTable<")
					.Append(itemClassName).Append(">(), \"").Append(table.stringID).AppendLine("\");");
			}

			Indent(sb, 2).AppendLine("}");
			Indent(sb, 1).AppendLine("}");
			sb.AppendLine();

			// Table item classes
			HashSet<string> uniqueTableItemTypes = new HashSet<string>();
			foreach (var table in root.tables)
			{
				if (string.IsNullOrEmpty(table.stringID))
					continue;

				// Skip predefined types
				if (string.Equals(table.stringID, "Logic", StringComparison.OrdinalIgnoreCase) ||
				    string.Equals(table.stringID, "Calendar", StringComparison.OrdinalIgnoreCase) ||
				    string.Equals(table.stringID, "CalendarV2", StringComparison.OrdinalIgnoreCase) ||
				    string.Equals(table.stringID, "Badges", StringComparison.OrdinalIgnoreCase) ||
				    string.Equals(table.stringID, "Graphs", StringComparison.OrdinalIgnoreCase))
				{
					continue;
				}

				string itemClassName = string.IsNullOrEmpty(table.itemClass) ? "SnipeTable" + table.stringID + "Item" : table.itemClass;

				// Some tables may share same item types. Don't emit them multiple tymes
				if (!uniqueTableItemTypes.Add(itemClassName))
				{
					continue;
				}

				Indent(sb, 1).AppendLine("[System.Serializable]");
				Indent(sb, 1).Append("public sealed class ").Append(itemClassName).AppendLine(" : SnipeTableItem");
				Indent(sb, 1).AppendLine("{");

				if (table.fields != null)
				{
					foreach (var field in table.fields)
					{
						if (!string.IsNullOrEmpty(field.name))
						{
							Indent(sb, 2).AppendLine("/// <summary>");
							Indent(sb, 2).Append("/// ").AppendLine(field.name);
							Indent(sb, 2).AppendLine("/// </summary>");
						}

						Indent(sb, 2).AppendLine("#if UNITY_EDITOR");
						Indent(sb, 2).AppendLine("[field:UnityEngine.SerializeField]");
						Indent(sb, 2).AppendLine("#endif");

						string csType = MapTypeToCs(field.type, null);
						Indent(sb, 2).Append("public ").Append(csType).Append(' ').Append(field.id)
							.AppendLine(" { get; set; }").AppendLine();
					}
				}

				Indent(sb, 1).AppendLine("}");
				sb.AppendLine();
			}
		}

		#endregion

		#region Helpers


		private static StringBuilder Indent(StringBuilder sb, int level)
		{
			for (int i = 0; i < level; i++)
				sb.Append('\t');
			return sb;
		}

		private static string EscapeXml(string text)
		{
			if (string.IsNullOrEmpty(text))
				return string.Empty;

			return text
				.Replace("&", "&amp;")
				.Replace("<", "&lt;")
				.Replace(">", "&gt;");
		}

		private static string MapTypeToCs(string type, string itemType)
		{
			if (string.IsNullOrEmpty(type))
				return "object";

			switch (type)
			{
				case "string":
					return "string";
				case "int":
				case "timestamp":
					return "int";
				case "arrayint":
					return "List<int>";
				case "float":
					return "float";
				case "boolean":
					return "bool";
				case "array":
					{
						string elementType = MapTypeToCs(itemType, null);
						return $"List<{elementType}>";
					}
				case "Dynamic":
				case "object":
				case "json":
					return "object";

				default:
					return type;
			}
		}

		private static string GetTypeDisplayName(string csType)
		{
			if (string.IsNullOrEmpty(csType))
				return "object";

			// Convert C# types to display names used in XML docs
			switch (csType)
			{
				case "string":
					return "String";
				case "int":
					return "Int";
				case "float":
					return "Float";
				case "bool":
					return "Bool";
				case "object":
					return "object";
				case "Dictionary<string, object>":
					return "object";
				default:
					// For List<T>, extract T and format as "Array<T>"
					if (csType.StartsWith("List<") && csType.EndsWith(">"))
					{
						string elementType = csType.Substring(5, csType.Length - 6);
						string displayElementType = GetTypeDisplayName(elementType);
						return $"Array of {displayElementType}";
					}
					return csType;
			}
		}

		#endregion

		#region JSON Parsing

		private static MetagenRoot ParseJson(string json)
		{
			try
			{
				var root = fastJSON.JSON.ToObject<MetagenRoot>(json);
				return root;
			}
			catch (Exception e)
			{
				Debug.LogError($"SnipeApiGenerator.ParseJson - exception: {e}");
				return null;
			}
		}

		#endregion

		#region Spec DTOs

		private sealed class MetagenRoot
		{
			public int projectID;
			public string projectStringID;
			public string projectName;
			public string snipeVersion;
			public string generatedAt;
			public string timeZone;
			public MetagenModule[] modules;
			public MetagenType[] types;
			public MetagenUserAttribute[] userAttributes;
			public MetagenGameVar[] gameVars;
			public MetagenTable[] tables;
			public MetagenMergeableRequest[] mergeableRequests;
		}

		private sealed class MetagenModule
		{
			public string name;
			public bool hasResponses;
			public MetagenMethod[] methods;
			public MetagenResponse[] responses;
		}

		private sealed class MetagenMethod
		{
			public string callName;
			public string messageType;
			public string[] doc;
			public MetagenField[] inputs;
			public MetagenField[] outputs;
			public string[] errorCodes;
			public string actionID;
			public bool mergeable;
		}

		private sealed class MetagenResponse
		{
			public string msgType;
			public string callName;
			public string[] doc;
			public MetagenField[] fields;
		}

		private sealed class MetagenField
		{
			public string name;
			public string type;
			public string itemType;
			public bool optional;
			public string description;
		}

		private sealed class MetagenType
		{
			public string name;
			public MetagenField[] fields;
		}

		private sealed class MetagenTable
		{
			public string stringID;
			public string itemClass;
			public MetagenTableField[] fields;
		}

		private sealed class MetagenTableField
		{
			public string id;
			public string name;
			public string type;
			public bool isAttr;
		}

		private sealed class MetagenMergeableRequest
		{
			public string messageType;
			public Dictionary<string, string> payload;
		}

		private sealed class MetagenUserAttribute
		{
			public string stringID;
			public string type;
			public string name;
			public string clientRead;
			public string clientWrite;
		}

		private sealed class MetagenGameVar
		{
			public string stringID;
			public string type;
			public string property;
			public string resolvedType;
			public MetagenField[] fields;
		}

		#endregion
	}
}
